"""「tex_search_img.ipynb」的副本

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hIYO4xYylyQWzkPU9EoWgJ8ex1-sbrkX
"""
# !pip install ftfy regex tqdm
# !pip install git+https://github.com/openai/CLIP.git
# !pip install -q ftfy regex tqdm

from PIL import Image
from torch.utils.data import Dataset, DataLoader
from torchvision.transforms import Compose, Resize, CenterCrop, ToTensor, Normalize
import numpy as np
import os
from ultralytics import YOLO
import cv2
import pandas as pd
# from rembg import remove
# import albumentations as A

# Define the image transformation
def preprocess(n_px):
    return Compose([
        Resize(n_px, interpolation=Image.BICUBIC),
        CenterCrop(n_px),
        ToTensor(),
        Normalize((0.48145466, 0.4578275, 0.40821073), (0.26862954, 0.26130258, 0.27577711)), # 常態分布 (RGB:0-255)
    ])
    
# Custom Dataset for fine-tuning
class ImageTextDataset(Dataset):
    def __init__(self, image_paths, texts, transform=None): # transform including resize, crop,..etc
        self.image_paths = image_paths
        self.texts = texts
        self.transform = transform
        
    def __len__(self):return len(self.image_paths)
    # magic method)，用來讓物件支援像「索引」一樣的存取行為，例如 obj[index]
    def __getitem__(self, idx): 
        image = Image.open(self.image_paths[idx]).convert("RGB")
        text = self.texts[idx]
        if self.transform:
            image = self.transform(image)
        return image, text

    # consider ViT-B/32 with input 224x224
    def resize_image(self, image:Image.Image, size = (224,224)): 
        return image.resize(size)
    
    # 拼接圖片
    def image_collage(self, out_dir="./result", thumb_width:int=300,  thumb_heigh:int=300):
        thumb_size = (thumb_width, thumb_heigh)
        num_thumb = 2
        # 每四張拼接一次
        for batch_idx in range(0, len(self.image_paths), num_thumb**2):
            batch = self.image_paths[batch_idx : batch_idx + num_thumb**2]
            bg = Image.new("RGB", (thumb_size[0] * num_thumb, thumb_size[1] * num_thumb), "#000000")
            for j, path in enumerate(batch):
                img = Image.open(path).convert("RGB")
                resize_img = self.resize_image(img, thumb_size)  # 假設 resize_image 回傳 PIL Image
                x = (j % 2) * thumb_size[0]
                y = (j // 2) * thumb_size[1]
                bg.paste(resize_img, (x, y))
            out_path = os.path.join(out_dir, f"concat_{batch_idx//4}.jpg")
            bg.save(out_path)
            print("saving collage successfully!")
    
    def image_overlay(self):
        pass

# 將數據整理成一張圖像對三種不同 caption JSON 格式
def aggregate_image_captions(image_path:str, captions:str):
    """
    Inputs:
        captions = "1. a man riding a bike\n2. a cyclist wearing a helmet\n3. an outdoor biking scene"
    Returns:
        images = ["img.jpg", "img.jpg", "img.jpg"]
        captions_lst = [
            "a man riding a bike",
            "a cyclist wearing a helmet",
            "an outdoor biking scene"
        ]
    """
    image = image_path


# 移除caption中重複的文字
def deduplicate_contxt(text: str, sep: str = "，"):
    """
    精確句子去重
    :param text: 原始文字
    :param sep: 切分符號，默認是 "。" (適用中文)
    :return: 去重後的文字
    """
    # 切分句子
    sentences = text.split(sep)
    # 去掉空字串並保留順序去重
    unique_sentences = list(dict.fromkeys([s.strip() for s in sentences if s.strip()]))
    # 拼回文字
    return sep.join(unique_sentences) + (sep if text.endswith(sep) else "")


def crop_objects(img_paths, model_path="./yolov8l.pt", output_dir="cropped_objects", conf_threshold=0.9):
    """
    使用 YOLOv8 模型偵測並裁切圖片中的物體，輸出到指定資料夾。

    Args:
        img_paths (list or str): 單張圖片路徑 (str) 或多張圖片路徑 (list)。
        model_path (str): YOLOv8 模型路徑，預設使用官方輕量模型。
        output_dir (str): 輸出裁切物體的資料夾。

    Returns:
        dict: {圖片路徑: [裁切後圖片路徑列表]}
    """
    # 確保輸出資料夾存在
    os.makedirs(output_dir, exist_ok=True)
    # 載入 YOLO 模型
    model = YOLO(model_path)
    # 若輸入單張圖片，自動轉成 list
    if isinstance(img_paths, str):
        img_paths = [img_paths]
    result_dict = {}
    for img_path in img_paths:
        results = model(img_path)
        print(115, f"預設有 80 類別 (COCO dataset):{model.names}")
        img = cv2.imread(img_path)
        cropped_files = []
        for i, box in enumerate(results[0].boxes):
            x1, y1, x2, y2 = map(int, box.xyxy[0])
            obj_img = img[y1:y2, x1:x2]
            out_path = os.path.join(
                output_dir,
                f"{os.path.splitext(os.path.basename(img_path))[0]}_obj_{i}.jpg"
            )
            cv2.imwrite(out_path, obj_img)
            cropped_files.append(out_path)
        result_dict[img_path] = cropped_files
    return result_dict

# 以 vlm 針對 yolo 切割後的照片，產生對應應圖片的單一概念描述
def vlm_generate_caption(image:str):
    Image.open(image)
    


if __name__=="__main__":
    # command "yolo settings" 可查看目前參數設定
    # crop_objects("origin_dataset/13274_632087950224364_8692510268907875417_n(1).jpg")
    df=pd.read_csv("captions_0924.csv")